[package]
name = "pfe-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
opentelemetry-proto = { version = "0.33", default-features = false, features = ["gen-tonic", "metrics", "trace"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tonic = { version = "0.14", features = ["gzip"] }
tonic-health = "0.14"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
