# Two independent Linux kernels. Host services run in Docker Compose.
Vagrant.require_version ">= 2.4.9", "< 3.0"

def environment_integer(name, default, minimum, maximum)
  value = Integer(ENV.fetch(name, default.to_s), 10)
  raise "#{name} must be between #{minimum} and #{maximum}" unless (minimum..maximum).cover?(value)
  value
end

port = environment_integer("TEST_ENV_HOST_PORT", 8088, 1024, 65535)
prometheus_port = environment_integer("TEST_ENV_PROMETHEUS_PORT", 9090, 1024, 65535)
cpus = environment_integer("TEST_ENV_NODE_CPUS", 1, 1, 4)
memory = environment_integer("TEST_ENV_NODE_MEMORY_MB", 1024, 512, 4096)

nodes = {
  "node1" => { "pfe_hostname" => "pfe-compute-1", "pfe_private_ip" => "192.168.56.11" },
  "node2" => { "pfe_hostname" => "pfe-compute-2", "pfe_private_ip" => "192.168.56.12" }
}

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-26.04"
  config.vm.box_version = "202606.01.0"
  config.vm.box_architecture = :auto
  config.vm.box_check_update = false
  config.vm.boot_timeout = 300
  # Avoid exposing the repository or host home directory in the guests.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  nodes.each do |name, variables|
    config.vm.define name do |node|
      node.vm.hostname = variables.fetch("pfe_hostname")
      node.vm.network "private_network", ip: variables.fetch("pfe_private_ip"), netmask: "255.255.255.0", virtualbox__intnet: "pfe-telemetry-test"
      node.vm.provider "virtualbox" do |provider|
        provider.name = "pfe-telemetry-test-#{name}"
        provider.gui = false
        provider.cpus = cpus
        provider.memory = memory
        # 10.0.2.2 on the NAT interface maps to the host loopback interface.
        provider.customize ["modifyvm", :id, "--nat-localhostreachable1", "on"]
      end
    end
  end

  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.playbook = "ansible/site.yml"
    ansible.config_file = "ansible/ansible.cfg"
    ansible.groups = {
      "compute" => nodes.keys,
      "compute:vars" => {
        "pfe_ingestion_address" => "10.0.2.2:#{port}",
        "pfe_prometheus_url" => "http://10.0.2.2:#{prometheus_port}"
      }
    }
    ansible.host_vars = nodes
  end
end
